=== rstehwien/Wild-Talents-Character-Creator/Resources/wtcc/xml/WildTalentsCharacterCreator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="data">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element minOccurs="0" ref="config-sets"/>
          <xs:element maxOccurs="unbounded" minOccurs="0" ref="config-chooser"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute form="unqualified" name="version" type="xs:integer" use="required"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="meta-qualities">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element ref="sources" minOccurs="0"/>
          <xs:element ref="permissions" minOccurs="0"/>
          <xs:element ref="intrinsics" minOccurs="0"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="archetypes">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="archetype" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="character">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element ref="infos" minOccurs="0"/>
          <xs:element ref="willpower" minOccurs="0"/>
          <xs:element ref="archetype" minOccurs="0"/>
          <xs:element ref="custom-modifiers" minOccurs="0"/>
          <xs:element ref="measurements" minOccurs="0"/>
          <xs:element maxOccurs="unbounded" minOccurs="0" ref="pools"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute form="unqualified" name="version" type="xs:integer" use="required"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute name="pointsArchetype" use="required" type="xs:integer"/>
      <xs:attribute name="pointsPowers" use="required" type="xs:nonNegativeInteger"/>
      <xs:attribute name="pointsSkills" use="required" type="xs:nonNegativeInteger"/>
      <xs:attribute name="pointsStats" use="required" type="xs:nonNegativeInteger"/>
      <xs:attribute name="pointsWillpower" use="required" type="xs:nonNegativeInteger"/>
      <xs:attribute name="points" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="infos">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="info" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="info">
    <xs:complexType mixed="true">
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="willpower">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="motivations"/>
      </xs:sequence>
      <xs:attribute name="base" use="required" type="xs:nonNegativeInteger"/>
      <xs:attribute name="current" use="required" type="xs:nonNegativeInteger"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute default="0" name="points" type="xs:nonNegativeInteger"/>
      <xs:attribute default="0" name="min-base" type="xs:nonNegativeInteger"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="motivations">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="motivation" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="motivation">
    <xs:complexType>
      <xs:attribute name="type" use="required" type="xs:string"/>
      <xs:attribute name="value" use="required" type="xs:nonNegativeInteger"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="custom-modifiers">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="effect" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="ref" type="xs:NCName" use="optional"/>
      <xs:attribute name="name" type="xs:string" use="optional"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="effects">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="effect" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="effect">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element minOccurs="0" ref="capacities"/>
          <xs:element minOccurs="0" ref="modifiers"/>
          <xs:element minOccurs="0" ref="measurements"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="type" use="required" type="xs:string"/>
      <xs:attribute name="cost" type="xs:nonNegativeInteger" default="0"/>
      <xs:attribute name="include-measurement" type="xs:boolean" default="false"/>
      <xs:attribute name="special" type="xs:string"/>
      <xs:attribute name="special-required" type="xs:boolean" default="false"/>
      <xs:attribute name="link" type="xs:NCName"/>
      <xs:attribute default="false" name="link-required" type="xs:boolean"/>
      <xs:attribute name="book" type="xs:string"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute default="0" name="die-cost" type="xs:nonNegativeInteger"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="pools">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="pool"/>
      </xs:sequence>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute default="0" name="points" type="xs:nonNegativeInteger"/>
      <xs:attribute name="type" type="xs:NCName" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="pool">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="effects" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="book" type="xs:string"/>
      <xs:attribute name="die-cost" type="xs:nonNegativeInteger" default="0"/>
      <xs:attribute name="hard" type="xs:nonNegativeInteger" default="0"/>
      <xs:attribute name="normal" type="xs:nonNegativeInteger" default="0"/>
      <xs:attribute name="type" type="xs:NCName"/>
      <xs:attribute name="wiggle" type="xs:nonNegativeInteger" default="0"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute default="0" name="points" type="xs:nonNegativeInteger"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="capacities">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="capacity"/>
      </xs:sequence>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string" use="optional"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute name="mod" use="optional" type="xs:integer" default="0"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="capacity">
    <xs:complexType>
      <xs:attribute name="mod" type="xs:integer" default="0"/>
      <xs:attribute name="type" type="xs:NCName"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="modifiers">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="modifier"/>
      </xs:sequence>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute name="mod" use="optional" type="xs:integer" default="0"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="modifier">
    <xs:complexType>
      <xs:attribute name="book" type="xs:string"/>
      <xs:attribute name="mod" use="optional" type="xs:integer" default="0"/>
      <xs:attribute name="special" type="xs:string"/>
      <xs:attribute name="special-required" type="xs:boolean" default="false"/>
      <xs:attribute name="has-ranks" type="xs:boolean" default="false"/>
      <xs:attribute name="ranks" type="xs:positiveInteger" default="1"/>
      <xs:attribute name="type" use="required" type="xs:string"/>
      <xs:attribute name="link" type="xs:NCName"/>
      <xs:attribute default="false" name="link-required" type="xs:boolean"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute name="cost" type="xs:integer" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sources">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="source" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="pick" type="xs:boolean" default="false"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="source">
    <xs:complexType>
      <xs:attribute name="book" type="xs:string"/>
      <xs:attribute name="cost" use="required" type="xs:integer"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="permissions">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="permission" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="permission">
    <xs:complexType>
      <xs:attribute name="book" type="xs:string"/>
      <xs:attribute name="cost" type="xs:integer" use="required"/>
      <xs:attribute name="custom" type="xs:boolean" default="false"/>
      <xs:attribute name="special" type="xs:string"/>
      <xs:attribute name="special-required" type="xs:boolean" default="false"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="intrinsics">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="intrinsic" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="intrinsic">
    <xs:complexType>
      <xs:attribute name="cost" type="xs:integer" use="required"/>
      <xs:attribute name="custom" type="xs:boolean" default="false"/>
      <xs:attribute name="special" type="xs:string"/>
      <xs:attribute name="special-required" type="xs:boolean" default="false"/>
      <xs:attribute name="book" type="xs:string"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="archetype">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element ref="sources" minOccurs="0"/>
          <xs:element ref="permissions" minOccurs="0"/>
          <xs:element minOccurs="0" ref="intrinsics"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="points" type="xs:integer" default="0"/>
      <xs:attribute name="book" type="xs:string"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="tables">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="measurements" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="measurements">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="measurement" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="beyond" type="xs:decimal"/>
      <xs:attribute name="boost" type="xs:decimal"/>
      <xs:attribute name="type" type="xs:NCName"/>
      <xs:attribute name="units" type="xs:string"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="measurement">
    <xs:complexType>
      <xs:attribute name="type" type="xs:NCName"/>
      <xs:attribute name="pool" use="required" type="xs:nonNegativeInteger"/>
      <xs:attribute name="text" type="xs:string"/>
      <xs:attribute name="units" type="xs:string"/>
      <xs:attribute name="value" type="xs:decimal"/>
      <xs:attribute name="example" type="xs:string"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="config-chooser">
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="effects" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="capacities" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element maxOccurs="unbounded" ref="archetypes" minOccurs="0"/>
          <xs:element ref="character" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="tables" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element maxOccurs="unbounded" minOccurs="0" ref="meta-qualities"/>
          <xs:element maxOccurs="unbounded" minOccurs="0" ref="pools"/>
          <xs:element maxOccurs="unbounded" minOccurs="0" ref="modifiers"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="ref" type="xs:NCName" use="optional"/>
      <xs:attribute name="name" type="xs:string" use="optional"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute name="type" type="xs:NCName" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="config-sets">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="config-set"/>
      </xs:sequence>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute name="chosen" type="xs:NCName" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="config-set">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="config-choice"/>
      </xs:sequence>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute default="true" name="build-skills" type="xs:boolean" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="config-choice">
    <xs:complexType>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string" use="optional"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute name="link" type="xs:NCName" use="required"/>
      <xs:attribute name="type" type="xs:NCName" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rstehwien/Wild-Talents-Character-Creator/Resources/wtcc/xml/WildTalentsCharacterCreatorData.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="WildTalentsCharacterCreator.xsd" version="1">

  <!-- 
    Notes 
    * all elements have a
      * id - unique identifier, optional
      * ref- reference for lookups, can have duplicates, optional
      * name - display name, optional
    * ref or id used when linking elements together
    * cost for stats and skills doesn't include Native modifier 
  -->

  <config-sets chosen="default">
    <config-set ref="default" name="All" build-skills="true">
      <config-choice type="effects" link="default_effects"/>
      <config-choice type="capacities" link="default_capacities"/>
      <config-choice type="stats" link="default_stats"/>
      <config-choice type="skills" link="_ALL_"/>
      <config-choice type="meta-qualities" link="_ALL_"/>
      <config-choice type="archetypes" link="_ALL_"/>
      <config-choice type="modifiers" link="_ALL_"/>
      <config-choice type="powers" link="_ALL_"/>
      <config-choice type="character" link="default_character"/>
      <config-choice type="tables" link="default_tables"/>
    </config-set>
  </config-sets>

  <config-chooser type="effects">
    <effects ref="default_effects">
      <effect type="stat" name="Stat" cost="4"/>
      <effect type="skill" name="Build" cost="0"/>
      <effect type="skill" name="Standard" cost="1"/>
      <effect type="power" name="Attacks" cost="2"/>
      <effect type="power" name="Defends" cost="2"/>
      <effect type="power" name="Useful" cost="2" special-required="true"/>
      <effect type="power" name="Dud" cost="1" special-required="true"/>
      <effect type="willpower-base" name="Base Willpower" cost="3"/>
      <effect type="willpower" name="Willpower" cost="1"/>
      <effect type="modifier" name="Custom Modifier" cost="0"/>
    </effects>
  </config-chooser>

  <config-chooser type="capacities">
    <capacities ref="default_capacities">
      <capacity type="power" name="Mass" mod="2"/>
      <capacity type="power" name="Range" mod="2"/>
      <capacity type="power" name="Speed" mod="2"/>
      <capacity type="power" name="Touch" mod="1"/>
      <capacity type="power" name="Self" mod="2"/>
      <capacity type="Body" name="Lift" mod="0"/>
      <capacity type="Body" name="Throw" mod="0"/>
      <capacity type="Body" name="Damage" mod="0"/>
      <capacity type="Body" name="Sprint" mod="0"/>
      <capacity type="Body" name="Long Jump" mod="0"/>
      <capacity type="Body" name="High Jump" mod="0"/>
    </capacities>
  </config-chooser>

  <config-chooser type="stats">
    <pools type="stats" ref="default_stats">
      <pool name="">
        <effects>
          <effect type="stat" name="Body" cost="4"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="stat" name="Coordination" cost="4"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="stat" name="Sense" cost="4"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="stat" name="Mind" cost="4"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="stat" name="Charm" cost="4"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="stat" name="Command" cost="4"/>
        </effects>
      </pool>
    </pools>
  </config-chooser>

  <config-chooser type="skills">
    <pools type="skills" ref="wild_talents_skills" name="Wild Talents">
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Athletics" link="Body" special-required="true" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Block" link="Body" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Brawling" link="Body" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Endurance" link="Body" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Melee Weapon" link="Body" special-required="true" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Dodge" link="Coordination" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Driving" link="Coordination" special-required="true" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Ranged Weapon" link="Coordination" special-required="true" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Stealth" link="Coordination" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Empathy" link="Sense" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Perception" link="Sense" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Scrutiny" link="Sense" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="First Aid" link="Mind" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Knowledge" link="Mind" special-required="true" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Language" link="Mind" special-required="true" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Medicine" link="Mind" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Navigation" link="Mind" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Research" link="Mind" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Security Systems" link="Mind" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Streetwise" link="Mind" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Survival" link="Mind" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Tatics" link="Mind" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Lie" link="Charm" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Performance" link="Charm" special-required="true" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Persuasion" link="Charm" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Interrogation" link="Command" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Intimidation" link="Command" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Leadership" link="Command" book="WT2E"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="1" name="Stability" link="Command" book="WT2E"/>
        </effects>
      </pool>
    </pools>

    <pools type="skills" ref="kerberos_club_build_skills" name="Kerberos Club">
      <!-- Basic Skills KC -->
      <pool name="">
        <effects>
          <effect type="skill" cost="0" name="Boxing" link="Body" book="KC"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="0" name="Lifting" link="Body" book="KC"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="0" name="Running" link="Body" book="KC"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="0" name="Sports" link="Body" book="KC"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="0" name="Wrestling" link="Body" book="KC"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="0" name="Acrobatics" link="Coordination" book="KC"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="0" name="Archery" link="Coordination" book="KC"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="0" name="Climb" link="Coordination" book="KC"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="0" name="Dodge" link="Coordination" book="KC"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
          <effect type="skill" cost="0" name="Evasion" link="Coordination" book="KC"/>
        </effects>
      </pool>
      <pool name="">
        <effects>
